<script>
	require = {
		baseUrl: "js",
		urlArgs: "rc={{ env('JS_FILES_VERSION', '1.0.0') }}", /* Incrementar valor para forzar carga de cache */
		"paths": {
			"jquery"     : "vendor/jquery/jquery.min",
			"jqueryui"   : "vendor/jquery-ui/jquery-ui.min",
			"underscore" : "vendor/lodash/lodash.min",
			"backbone"   : "vendor/backbone/backbone",
			"marionette" : "vendor/marionette/lib/backbone.marionette.min",
			"wreqr"      : "vendor/backbone.wreqr/lib/backbone.wreqr.min",
			"fetchcache" : "vendor/backbone-fetch-cache/backbone.fetch-cache.min",
			"oscura"     : "vendor/backbone.obscura/backbone.obscura",
			"validation" : "vendor/backbone-validation/dist/backbone-validation-amd-min",
			"formparams" : "vendor/form-params/dist/jquery.formparams.min",
			"toggle"     : "vendor/bootstrap-switch/dist/js/bootstrap-switch.min",
			"messenger"  : "vendor/messenger/build/js/messenger.min",
			"messflat"   : "vendor/messenger/build/js/messenger-theme-flat",
			"bmodal"     : "vendor/bootstrap-modal/js/bootstrap-modal",
			"bmodal-man" : "vendor/bootstrap-modal/js/bootstrap-modalmanager",
			"fileupload" : "vendor/jquery-file-upload/js/jquery.fileupload",
			"futransport": "vendor/jquery-file-upload/js/jquery.iframe-transport",
			"numeraljs"  : "vendor/numeraljs/min/numeral.min",
			"chart"      : "vendor/highcharts/highcharts",
			"fecha"      : "vendor/fecha/fecha.min",
			"bootstrap"  : "vendor/bootstrap/dist/js/bootstrap.min",
			"gmap3"      : "vendor/gmap3/dist/gmap3.min",
			"mcsp"       : "vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar",
			"jqmw"       : "vendor/jquery-mousewheel/jquery.mousewheel",
			"datepicker" : "vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min",
			// "swig"       : "vendor/swig/browser/index",
			"swig"       : "libs/swig-1.4.2",
			"download"   : "libs/jquery.fileDownload",
			"jquery.ui.widget" : "libs/jquery.ui.widget",
			"moment"     : "vendor/moment/min/moment-with-locales.min",
			"daterange"  : "vendor/bootstrap-daterangepicker/daterangepicker",
			"chartjs"    : "vendor/Chart.js/dist/Chart",
			"flotbase"   : "vendor/flot/jquery.flot",
			"flotresize" : "vendor/flot/jquery.flot.resize",
			"flotcurved" : "vendor/flot.curvedlines/curvedLines",
			"flottime"   : "vendor/flot/jquery.flot.time",
			"numeral"    : "core/numeral",
			"mixins"     : "core/mixins",
			"msgBus"     : "core/msgBus",
			"modal"      : "core/modal",
			"resolver"   : "core/resolver",
			"selector"   : "core/materialSelector",
			"exportar"   : "core/models/exportar",
			"themecfg"   : "admintheme-config",
			"admintheme" : "../theme/js/app",
			"waves"      : "vendor/Waves/dist/waves.min"
		},
		"shim": {
			"download"   : ['jquery'],
			"formparams" : ['jquery'],
			"bootstrap"  : ['jquery'],
			"kendo"      : ['jquery'],
			"toggle"     : ['jquery'],
			"bmodal-man" : ['jquery'],
			"messenger"  : ['jquery'],
			"jqmw"       : ['jquery'],
			"messflat"   : ['messenger'],
			"jquery.ui.widget" : ['jquery'],
			"fileupload" : ['futransport' ],
			"bmodal"     : ['jquery','bmodal-man'],
			"gmap3"      : ['jquery', 'googlemaps'],
			"mcsp"       : ['jqmw'],
			"admintheme" : ['jquery', 'mcsp', 'themecfg'],
			"flotbase"   : ['jquery'],
			"flotresize" : ['flotbase'],
			"flottime"   : ['flotbase'],
			"flotcurved" : ['flotresize']
		},
		"deps": [
			"bootstrap",
			"formparams",
			"daterange",
			// "fetchcache",
			'main'
		]
	};
</script>
